### PR TITLE
close #23 track shots

### LINKED ISSUE #23: track shots
## Concept

Add [FiredMan](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#FiredMan) EH to all players (and all AI, if AI is being tracked):

```
_unit addEventHandler ["FiredMan", {
	params ["_unit", "", "", "", "", "", "_projectile", "_vehicle"];

    // a projectile is being tracked already
    if (_unit getVariable ["grad_replay_projectileTrackingRunning",false]) exitWith {};
        
    _unit setVariable ["grad_replay_projectileTrackingRunning",true];

    // track projectile
    _lastProjectilePos = [0,0,0];
    [{
        params ["_args","_handle"];
        _args params ["_projectile","_unit","_lastProjectilePos"];

        if (!isNull _projectile) then {
            _lastProjectilePos resize 0;
            _lastProjectilePos append (getPos _projectile);
        } else {
            _lastProjectilePos resize 2;
            _unit setVariable ["grad_replay_firedTarget",_lastProjectilePos];
            [_handle] call CBA_fnc_removePerFrameHandler;
            _unit setVariable ["grad_replay_projectileTrackingRunning",false];
        };
    },0,[_projectile,_unit,_lastProjectilePos]] call CBA_fnc_addPerFrameHandler;
}];
```

fn_startRecord:

```
...
_firedTarget = _unit getVariable "grad_replay_firedTarget";
if (!isNil "_firedTarget") then {
    /* do the saving */
    _unit setVariable ["grad_replay_firedTarget",nil];
};
...
```

### PR DESCRIPTION
**Pull request by McDiod**
Track shots of all tracked units.

## latest video
https://youtu.be/8yzb9G6uNrw

## older videos
https://youtu.be/DJx1-xSQMp8
https://youtu.be/A49nySbgScQ
https://youtu.be/kTnGQZSHAhs

### CODE REVIEW

**Comment by nomisum** [comment]
awesome! how about red lines for better visibility :smirk:

**Comment by Dahlgren** [comment]
Preferably apply the side color to the lines so you can see who is shooting if there are multiple players in one location

**Comment by DerZade** [comment]
@Dahlgren Looks like that's already the case. Check out the second video 😉

**Comment by Dahlgren** [comment]
🥇

**Comment by nomisum** [comment]
to me it looks like the order of the replay fragments is wrongly assembled in some cases, which leads to stuttering especially in the beginning of the recording (little judder)

**Comment by McDiod** [comment]
Had projectile speed mistakenly set to 4000 m/s. Video of test 3 now shows a speed of 600 m/s which I think looks good. It also shows a bug where the projectile will move back one tick at the end of its travel.

Discussion of stuttering in issue #26.

**Comment by McDiod** [comment]
Here's a different style of projectile animation, the way AAR does it. I think I prefer it over the continuous lines.

https://youtu.be/kTnGQZSHAhs

**Comment by McDiod** [comment]
Alright, tested on dedicated and cleaned it up a bit. I suggest we do the caliber differentiating in a separate PR @nomisum .

Can be merged. Latest testmission is `grad-replay_trackShots_test4.Altis` on our servers.

**Pull request merged**
