### PR TITLE
save & restore Game

### PR DESCRIPTION
**Pull request by Salbei2500**
Enhancing the replay tool with the ability to make ingame freezes. Having a look at the replay and then resuming.

### CODE REVIEW

**Review by nomisum — COMMENTED** [review]
i still need to review and test this 😲

**Comment by Salbei2500** [comment]
It's not in a mergable state atm :D

**Comment by nomisum** [comment]
good to know. (i didnt expect otherwise 😋 )

**Comment by McDiod** [comment]
grad-replay already freezes the game while the replay is playing, using `_x enableSimulationGlobal false;`. Can't you just re-enable the simulation to resume?

**Comment by nomisum** [comment]
i also heal every unit, so health must be restored to previous fucked up state as well...

**Pull request closed without merging**
